name: Update Scryfall Data

on:
  schedule:
    - cron: '0 0 * * 0'  # Run once a week (Sunday at midnight)
  workflow_dispatch:  # Allow manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Python (for splitting script)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Download the latest Scryfall data
      - name: Download Scryfall data
        run: |
          curl -o all-cards.json https://data.scryfall.io/all-cards/all-cards-20250423092734.json

      # Step 4: Run the pre-written Python script to split the data
      - name: Run split script
        run: python3 scripts/split_cards.py

      # Step 5: Commit and push updates
      - name: Commit and push updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add card_chunks/*.json
          git commit -m "Update Scryfall data chunks" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/gvt5036/Sharpie-Cube-Search.git HEAD:main
