name: Update Scryfall Data

on:
  schedule:
    - cron: '0 0 * * 0'  # Run once a week (Sunday at midnight)
  workflow_dispatch:  # Allow manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Python (for splitting script)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Download the latest Scryfall data
      - name: Download Scryfall data
        run: |
          curl -o all-cards.json https://data.scryfall.io/all-cards/all-cards-20250423092734.json

      # Step 4: Split
