name: Download Scryfall Chunk Files

on:
  schedule:
    - cron: '0 0 * * 0' # This means every Sunday at midnight UTC
  workflow_dispatch: # Allows manual triggering if needed

jobs:
  download-chunks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Scryfall Chunk 1
      run: |
        curl -L https://data.scryfall.io/all-cards/all-cards-20250423092734.json -o chunk_1.json
        echo "Chunk 1 downloaded successfully."

    - name: Download Scryfall Chunk 2
      run: |
        curl -L https://data.scryfall.io/all-cards/all-cards-20250423092735.json -o chunk_2.json
        echo "Chunk 2 downloaded successfully."

    - name: Commit the new chunks to the repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add chunk_1.json chunk_2.json
        git commit -m "Update Scryfall card chunks"
        git push

