name: Update Slimmed MTG Data

on:
  schedule:
    - cron: '0 5 * * 1'  # Every Monday at 5 AM UTC
  workflow_dispatch:     # Allow manual triggering too

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run slim script
        run: node scripts/slim.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add cards.json
          git commit -m "chore: update slimmed MTG data" || echo "No changes to commit"
          git push
