name: Update Scryfall Data

on:
  schedule:
    - cron: '0 0 * * 0'  # Run once a week (Sunday at midnight)
  workflow_dispatch:  # Allow manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Python (for splitting script)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Download the latest Scryfall data
      - name: Download Scryfall data
        run: |
          curl -o all-cards.json https://data.scryfall.io/all-cards/all-cards-20250423092734.json

      # Step 4: Split the data into chunks by first letter
      - name: Split data into chunks
        run: |
          mkdir -p card_chunks
          python3 <<EOF
import json, os
from collections import defaultdict

with open('all-cards.json', 'r', encoding='utf-8') as f:
    cards = json.load(f)

buckets = defaultdict(list)
for card in cards:
    first = card.get('name', 'unknown')[0].lower()
    if not first.isalpha():
        first = 'symbols'
    buckets[first].append(card)

os.makedirs('card_chunks', exist_ok=True)
for key, value in buckets.items():
    with open(f'card_chunks/{key}.json', 'w', encoding='utf-8') as out:
        json.dump(value, out, indent=2)
EOF
import json, os
from collections import defaultdict

with open('all-cards.json', 'r', encoding='utf-8') as f:
    cards = json.load(f)

buckets = defaultdict(list)
for card in cards:
    first = card.get('name', 'unknown')[0].lower()
    if not first.isalpha():
        first = 'symbols'
    buckets[first].append(card)

os.makedirs('card_chunks', exist_ok=True)
for key, value in buckets.items():
    with open(f'card_chunks/{key}.json', 'w', encoding='utf-8') as out:
        json.dump(value, out, indent=2)
EOF

      # Step 5: Commit and push updates
      - name: Commit and push updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add card_chunks/*.json
          git commit -m "Update Scryfall data chunks" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/gvt5036/Sharpie-Cube-Search.git HEAD:main
