name: Update Scryfall Data

on:
  schedule:
    - cron: '0 0 * * 0'  # Run once a week (Sunday at midnight)
  workflow_dispatch:  # Allow manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Timeout set to 60 minutes (adjust as needed)

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Python and ijson (for splitting script)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install ijson
        run: pip install ijson

      # Step 3: Download the latest Scryfall data
      - name: Download Scryfall data
        run: |
          curl -o all-cards.json https://data.scryfall.io/all-cards/all-cards-20250423092734.json

      # Step 4: Write the Python script to split the data
      - name: Write Python split script
        run: |
          cat <<EOF > scripts/split_cards.py
import ijson
import os
from collections import defaultdict
import json

# Create the 'card_chunks' directory if it doesn't exist
os.makedirs('card_chunks', exist_ok=True)

# Initialize the buckets for the cards
buckets = defaultdict(list)

# Open the JSON file and stream through it
with open('all-cards.json', 'r', encoding='utf-8') as f:
    objects = ijson.items(f, 'item')  # 'item' refers to the top-level elements in the JSON array
    for i, card in enumerate(objects):
        if i % 1000 == 0:  # Log every 1000 cards processed
            print(f"Processed {i} cards...")
        first = card.get('name', 'unknown')[0].lower()
        if not first.isalpha():
            first = 'symbols'
        buckets[first].append(card)

# Write out each bucket to a separate file
for key, value in buckets.items():
    with open(f'card_chunks/{key}.json', 'w', encoding='utf-8') as out:
        json.dump(value, out, indent=2)
EOF

      # Step 5: Run the Python script to split the data
      - name: Run split script
        run: python3 scripts/split_cards.py

      # Step 6: Commit and push updates
      - name: Commit and push updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add card_chunks/*.json
          git commit -m "Update Scryfall data chunks" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/gvt5036/Sharpie-Cube-Search.git HEAD:main
