name: Update Scryfall Data

on:
  schedule:
    - cron: '0 0 * * 0'  # Run once a week (Sunday at midnight)
  workflow_dispatch:  # Allow manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (or other runtime if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies (if needed)
      - name: Install dependencies
        run: |
          npm install  # Or your relevant install command

      # Step 4: Download and process the Scryfall data
      - name: Download Scryfall data
        run: |
          curl -o all-cards.json https://data.scryfall.io/all-cards/all-cards-20250423092734.json

      # Step 5: Commit and push the changes to the repository
      - name: Commit and push updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add all-cards.json
          git commit -m "Update Scryfall data"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
